# Generated by Django 3.2.7 on 2021-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(max_length=100)),
                ('page_content', models.TextField()),
                ('page_image', models.ImageField(upload_to='page/')),
            ],
        ),
    ]
