# Generated by Django 3.2.7 on 2021-09-16 05:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_Page',
            fields=[
                ('About_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('About_page_title', models.CharField(max_length=100)),
                ('About_page_content', tinymce.models.HTMLField()),
                ('About_page_image', models.ImageField(upload_to='page/')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
