# Generated by Django 3.2.7 on 2021-09-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210916_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_Page',
            new_name='aboutPage',
        ),
    ]
