# Generated by Django 3.2.7 on 2021-09-16 05:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_about_page_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactPage',
            fields=[
                ('contact_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_page_title', models.CharField(max_length=100)),
                ('contact_page_content', tinymce.models.HTMLField()),
                ('contact_page_image', models.ImageField(upload_to='page/')),
            ],
        ),
        migrations.CreateModel(
            name='privacyPage',
            fields=[
                ('privacy_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('privacy_page_title', models.CharField(max_length=100)),
                ('privacy_page_content', tinymce.models.HTMLField()),
                ('privacy_page_image', models.ImageField(upload_to='page/')),
            ],
        ),
    ]
