# Generated by Django 3.2.7 on 2021-09-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuOnHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_sub_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_sub_menu_item', to='blog.category')),
            ],
            options={
                'verbose_name': 'Header Sub Menu item',
                'verbose_name_plural': 'header Sub Menu',
                'db_table': 'headersubmenu',
            },
        ),
    ]
