# Generated by Django 3.2.7 on 2021-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default=1, upload_to='user/'),
            preserve_default=False,
        ),
    ]
