# Generated by Django 3.2.7 on 2021-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_user_description_profile_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_fcebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='author_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
