# Generated by Django 3.2.7 on 2021-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210916_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='favicon',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='site_logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
