# Generated by Django 3.2.7 on 2021-09-17 09:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210916_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
