# Generated by Django 3.2.7 on 2021-09-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_url',
            field=models.URLField(blank=True, default='webdeck.ml', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Dhaka, bangladesh', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(blank=True, default='Creative'),
        ),
    ]
