# Generated by Django 3.2.7 on 2021-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210918_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_fcebook_link',
            field=models.URLField(blank=True, default='https://www.facebook.com/ronytarafder99', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='author_url',
            field=models.URLField(blank=True, default='https://webdeck99.blogspot.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='https://scontent.fdac68-1.fna.fbcdn.net/v/t39.30808-6/240813183_557193095424724_4523825855002356367_n.jpg?_nc_cat=100&_nc_rgb565=1&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=AmW8i4jQuBgAX_GWmOQ&tn=cZIseZIUe3HLced-&_nc_ht=scontent.fdac68-1.fna&oh=fb1f94070439265e1465dde56653788d&oe=61499E4A', upload_to='user/'),
        ),
    ]
